// Physics: receives thrust forces (Newtons, world frame) for all vehicles.
// Adds gravity and the current wind gust, integrates F=ma into velocity
// and position. Bounces off the ground.
//
// Wind is generated by the top-level `wind` block; the config wires its
// fx/fz into this block's mapStateIn.

type Vec3 = { x: number; y: number; z: number };
type VehicleIn = { pos: Vec3; vel: Vec3; actual: Vec3 };
type VehicleOut = { pos: Vec3; vel: Vec3; acc: Vec3 };
type WorldIn = { vehicles: Record<string, VehicleIn>; windFx: number; windFz: number };
type WorldOut = { vehicles: Record<string, VehicleOut> };

const DT = 0.05;
const MASS = 1.0;
const GRAVITY = 9.81;

function simulateVehicle(v: VehicleIn, windFx: number, windFz: number): VehicleOut {
  const ax = (v.actual.x + windFx) / MASS;
  const ay = (v.actual.y - MASS * GRAVITY) / MASS;
  const az = (v.actual.z + windFz) / MASS;

  let vx = v.vel.x + ax * DT;
  let vy = v.vel.y + ay * DT;
  let vz = v.vel.z + az * DT;
  let x = v.pos.x + vx * DT;
  let y = v.pos.y + vy * DT;
  let z = v.pos.z + vz * DT;

  if (y < 0) {
    y = 0;
    vy = Math.abs(vy) * 0.3;
  }

  return { pos: { x, y, z }, vel: { x: vx, y: vy, z: vz }, acc: { x: ax, y: ay, z: az } };
}

export function world(state: WorldIn): WorldOut {
  const vehicles: Record<string, VehicleOut> = {};
  for (const [key, vehicle] of Object.entries(state.vehicles)) {
    vehicles[key] = simulateVehicle(vehicle, state.windFx, state.windFz);
  }
  return { vehicles };
}
